# syntax=docker/dockerfile:1.7

# ─── deps ────────────────────────────────────────────────────────────────────
# Install production deps in an isolated layer so they cache across rebuilds.
FROM node:20-alpine AS deps
WORKDIR /app

# libc6-compat is needed by some Next/SWC native binaries on Alpine.
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci


# ─── builder ─────────────────────────────────────────────────────────────────
# Build the standalone Next.js bundle. NEXT_PUBLIC_* env values are baked into
# the client JS at build time — pass them as --build-arg.
FROM node:20-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID

# Skip Next.js anonymous telemetry inside CI builds.
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build


# ─── runner ──────────────────────────────────────────────────────────────────
# Minimal image that runs only the standalone server. No npm, no source, no
# node_modules copy — only what `output: "standalone"` produced.
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# PORT and HOSTNAME are intentionally NOT hard-coded here — docker-compose
# (or `docker run -e PORT=…`) injects them at runtime so the same image can
# bind to any port.
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Drop root.
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 --ingroup nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
# EXPOSE is metadata only — the actual port comes from $PORT at runtime.
EXPOSE 3000

# server.js is generated by Next when output:"standalone" is enabled.
# It reads $PORT and $HOSTNAME from the environment, so changing PORT in
# docker-compose / .env is enough — no rebuild required.
CMD ["node", "server.js"]
